/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cboton;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Abi
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        campoEdad = new javax.swing.JTextField();
        evento = new Eventos();
        botonInsertar = new javax.swing.JButton();
        evento = new Eventos();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(campoNombre);
        campoNombre.setBounds(130, 40, 190, 25);
        getContentPane().add(campoEdad);
        campoEdad.setBounds(130, 80, 100, 25);

        botonInsertar.setText("Insertar");
        botonInsertar.addActionListener(evento);
        getContentPane().add(botonInsertar);
        botonInsertar.setBounds(80, 190, 110, 23);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(evento);
        getContentPane().add(botonEliminar);
        botonEliminar.setBounds(230, 190, 120, 23);

        setSize(new java.awt.Dimension(481, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonInsertar;
    private Eventos evento;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoNombre;
    // End of variables declaration//GEN-END:variables

    
    /* Creamos la clase interna */
    private class Eventos implements ActionListener {

        private PersonaDAO laPersonaDAO = new PersonaDAO();
        
        private Persona obtenerDatosFormulario() {
            Persona laPersona = new Persona();
            
            laPersona.setNombre(campoNombre.getText());
            laPersona.setEdad(Integer.parseInt(campoEdad.getText()));
            
            return laPersona;
        }
        
        
        @Override
        public void actionPerformed(ActionEvent e) {
            
            /* UTILIZANDO GETACTIONCOMMAND */
            String textoDelBoton = e.getActionCommand();
            System.out.println("Texto del boton: " + textoDelBoton);
            
            if (textoDelBoton.equals("Insertar")) {
                laPersonaDAO.insertar(obtenerDatosFormulario());        
            }
            
            /* UTILIZANDO GETSOURCE */
            Object fuente = e.getSource();
            if (fuente.equals(botonInsertar)){
                laPersonaDAO.insertar(obtenerDatosFormulario());
            }
        }
        
    }
    
}