/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PersonaEvento;

/**
 *
 * @author Abi
 */
public class PersonaVentana extends javax.swing.JFrame {

    /**
     * Creates new form PersonaGUI
     */
    public PersonaVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        campoEstatura = new javax.swing.JTextField();
        campoDatos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 20);

        campoNombre.setText("abi");
        getContentPane().add(campoNombre);
        campoNombre.setBounds(130, 40, 180, 25);

        jLabel2.setText("Edad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 70, 14);

        campoEdad.setText("28");
        getContentPane().add(campoEdad);
        campoEdad.setBounds(130, 90, 80, 25);

        jLabel3.setText("Estatura");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 70, 30);

        botonAceptar.setText("Aceptar");
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(120, 190, 100, 30);
        PersonaEvento evento = new PersonaEvento(campoNombre, campoEdad, campoEstatura, campoDatos, botonAceptar);

        campoEstatura.setText("1.62");
        getContentPane().add(campoEstatura);
        campoEstatura.setBounds(130, 150, 70, 25);
        getContentPane().add(campoDatos);
        campoDatos.setBounds(310, 120, 250, 30);

        setSize(new java.awt.Dimension(596, 301));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonaVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoDatos;
    private javax.swing.JTextField campoEdad;
    private javax.swing.JTextField campoEstatura;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
