/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Abi
 */
public class MaestroVentana extends javax.swing.JFrame {

    /**
     * Creates new form MaestroVentana
     */
    public MaestroVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuOpciones = new javax.swing.JMenu();
        itemAgregar = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();
        itemModificar = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        menuArchivo.setText("Archivo");
        BarraMenu.add(menuArchivo);

        menuOpciones.setText("Opciones");

        itemAgregar.setText("Agregar");
        itemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarActionPerformed(evt);
            }
        });
        menuOpciones.add(itemAgregar);

        itemListar.setText("Listar");
        menuOpciones.add(itemListar);

        itemModificar.setText("Modificar");
        menuOpciones.add(itemModificar);

        itemEliminar.setText("Eliminar");
        menuOpciones.add(itemEliminar);

        BarraMenu.add(menuOpciones);

        setJMenuBar(BarraMenu);

        setSize(new java.awt.Dimension(636, 184));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarActionPerformed
        MaestroAgregar ma = new MaestroAgregar(this, rootPaneCheckingEnabled);
        ma.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_itemAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaestroVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem itemAgregar;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenuItem itemModificar;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuOpciones;
    // End of variables declaration//GEN-END:variables
}
